import { test, expect } from "@playwright/test";

// Generated by One Touch E2E for BOK-21.
// Steps and expectations from the approved manual cases are preserved as
// comments so a human can flesh out selectors without losing intent.
const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

test.describe("ViewArticleOnWikipedia (web)", () => {
  test("TC-01 Anonymous user successfully searches for and views a Wikipedia article", async ({ page }) => {
    // step: Open the browser in a private/incognito window.
    // step: Navigate to https://www.wikipedia.org.
    // step: Confirm the homepage loads without any login or registration prompt.
    // step: Click the search bar on the homepage.
    // step: Type the topic 'Machine learning' in the search bar.
    // step: Press Enter (or click the search/magnifier button) to submit the search.
    // step: Observe the page that loads.
    // step: Scroll through the article from top to bottom.
    // expect: The Wikipedia homepage is accessible to an anonymous user without login.
    // expect: The search bar accepts the typed text and may display search suggestions.
    // expect: After submitting, the 'Machine learning' article page loads successfully with HTTP 200 and no error message.
    // expect: The article title, introduction, table of contents, section headings and body text are displayed.
    // expect: Article text is clearly visible and readable (no truncated, overlapping or blank content) and images/links render correctly.
    // expect: The full article content is viewable without any paywall, login prompt or access restriction.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-02 Submitting an empty search returns a blank page with no search results", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Do not type any character (leave the field empty).
    // step: Press Enter to submit the search.
    // step: Observe the resulting page.
    // expect: A blank search page is displayed with no search results listed.
    // expect: No article is opened and no result count is shown.
    // expect: No unexpected system error, stack trace or broken page is displayed.
    // expect: The search bar remains available for a new search.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-03 Searching an invalid/non-existent term shows 'There were no results matching the query'", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Type the invalid text 'qwrtyplkjhgfdzxcvbnm12345'.
    // step: Press Enter to submit the search.
    // step: Observe the resulting search results page.
    // expect: The search results page loads successfully.
    // expect: The message 'There were no results matching the query' is displayed.
    // expect: No article page is opened and no result entries are listed.
    // expect: The searched text is retained in the search bar so the user can correct it.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-04 Search text longer than 500 characters shows maximum length error message", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Paste the prepared 600-character string into the search bar.
    // step: Press Enter to submit the search.
    // step: Observe the resulting page and message.
    // expect: The search is rejected and no article or result list is displayed.
    // expect: The error message 'An error has occurred while searching: Search request is longer than the maximum allowed length' is displayed.
    // expect: The page remains stable and usable (no crash, blank page or unhandled server error).
    // expect: The user can clear the field and perform a new valid search.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-05 Boundary: search text of exactly 500 characters is accepted without length error", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Paste the prepared 500-character string into the search bar.
    // step: Verify the character count of the pasted text is exactly 500.
    // step: Press Enter to submit the search.
    // step: Observe the resulting page and message.
    // expect: The search request is processed and the search results page loads.
    // expect: The message 'An error has occurred while searching: Search request is longer than the maximum allowed length' is NOT displayed.
    // expect: Either matching results are listed or the message 'There were no results matching the query' is displayed, depending on the content searched.
    // expect: No system crash or unhandled error occurs.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-06 Boundary: search text of 501 characters triggers maximum length error message", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Paste the prepared 501-character string into the search bar.
    // step: Verify the character count of the pasted text is exactly 501.
    // step: Press Enter to submit the search.
    // step: Observe the resulting page and message.
    // expect: The search is rejected and no results are returned.
    // expect: The error message 'An error has occurred while searching: Search request is longer than the maximum allowed length' is displayed.
    // expect: The message text matches exactly as specified in the acceptance criteria.
    // expect: The page remains functional and a new valid search can be executed.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
});
