import { test, expect } from "@playwright/test";

// Generated by One Touch E2E for BOK-21.
// Steps and expectations from the approved manual cases are preserved as
// comments so a human can flesh out selectors without losing intent.
const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

test.describe("ViewArticleOnWikipedia (web)", () => {
  test("TC-01 Anonymous user can search a topic on Wikipedia homepage and view the article (happy path)", async ({ page }) => {
    // step: Open the browser in a private/incognito window.
    // step: Navigate to https://www.wikipedia.org.
    // step: Confirm the homepage loads without prompting for login or registration.
    // step: Click the search bar on the homepage.
    // step: Type the topic 'Artificial intelligence'.
    // step: Press Enter (or click the search/magnifier button).
    // step: Wait for the result page to load.
    // step: Scroll through the loaded article from top to bottom.
    // expect: The Wikipedia homepage is fully accessible to an anonymous user with no login barrier.
    // expect: The search bar accepts the typed text and displays matching suggestions.
    // expect: After submitting, the 'Artificial intelligence' article page loads successfully with HTTP 200 and no error message.
    // expect: The article title matches the searched topic and the introductory summary, sections, headings and images are displayed.
    // expect: Article body text is clearly visible and readable (no truncated, overlapping or blank content) and remains viewable without login.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-02 Selecting a topic from search bar autocomplete suggestions opens the correct article", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Type the partial text 'Solar sys'.
    // step: Wait for the suggestion dropdown to appear.
    // step: Click the suggestion 'Solar System'.
    // step: Wait for the page to load.
    // expect: A suggestion dropdown appears listing topics matching 'Solar sys'.
    // expect: The 'Solar System' article page opens directly without an intermediate search results page.
    // expect: The article heading reads 'Solar System' and the content is fully readable.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-03 Negative - Submitting an empty search bar returns a blank page with no search results", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Do not type any characters (leave the field empty).
    // step: Press Enter (or click the search/magnifier button).
    // step: Observe the resulting page.
    // expect: No article page is opened.
    // expect: A blank search page is displayed with no search results listed.
    // expect: No application crash, stack trace or unexpected error page is shown.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-04 Negative - Invalid/nonsense search text returns 'There were no results matching the query'", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Type the invalid text 'qwzxjklmnpvbhgtrd12345'.
    // step: Press Enter (or click the search/magnifier button).
    // step: Observe the resulting page.
    // expect: The search results page loads without any article being opened.
    // expect: The message 'There were no results matching the query' is displayed.
    // expect: The search bar remains available so the user can retry with different text.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-05 Negative - Search text longer than 500 characters shows maximum length error message", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Paste the prepared 600-character string into the search bar.
    // step: Press Enter (or click the search/magnifier button).
    // step: Observe the resulting page and the displayed message.
    // expect: No article or result list is returned.
    // expect: The error message 'An error has occurred while searching: Search request is longer than the maximum allowed length' is displayed.
    // expect: The page remains usable and the user can clear the field and search again.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-06 Boundary - Search text of exactly 500 characters is accepted while 501 characters triggers the length error", async ({ page }) => {
    // step: Click the search bar on the Wikipedia homepage.
    // step: Paste the 500-character string into the search bar and verify the character count is exactly 500.
    // step: Press Enter to submit the search.
    // step: Observe the resulting page and message.
    // step: Clear the search bar completely.
    // step: Paste the 501-character string and verify the character count is exactly 501.
    // step: Press Enter to submit the search.
    // step: Observe the resulting page and message.
    // expect: For the 500-character search, the length error message is NOT displayed; the search is processed and either results or 'There were no results matching the query' is shown.
    // expect: For the 501-character search, the error message 'An error has occurred while searching: Search request is longer than the maximum allowed length' is displayed.
    // expect: In both cases the page loads without crashing and the search bar retains focus/usability.
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
});
