import { test, expect } from "@playwright/test";

// Generated by One Touch E2E for BOK-21.
// Steps and expectations from the approved manual cases are preserved as
// comments so a human can flesh out selectors without losing intent.
const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

test.describe("ViewArticleOnWikipedia (web)", () => {
  test("TC-01 Search for a valid topic from the Wikipedia homepage and view the article (happy path)", async ({ page }) => {
    // step: Open the browser and navigate to https://www.wikipedia.org
    // step: Select the English language edition (or navigate to https://en.wikipedia.org)
    // step: Click into the search bar on the homepage
    // step: Type the topic 'Artificial intelligence'
    // step: Press Enter or click the search/magnifier button
    // step: If a results list is displayed, click the article titled 'Artificial intelligence'
    // step: Scroll through the article from top to bottom
    // expect: The Wikipedia homepage loads without prompting for login or registration
    // expect: The search bar accepts the typed text and shows suggestions
    // expect: After submitting, the 'Artificial intelligence' article page loads successfully with HTTP 200 and no error banner
    // expect: The article title, introductory summary, table of contents, section headings and body text are displayed
    // expect: Article content is legible (no overlapping/truncated text) and scrolls smoothly to the end of the page
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-02 Verify article is fully accessible to an anonymous user without login", async ({ page }) => {
    // step: Open a private/incognito browser window
    // step: Navigate to https://en.wikipedia.org
    // step: Search for 'Solar System' using the search bar and submit
    // step: Observe the loaded article page and the top-right user area
    // step: Click any internal link inside the article body (for example 'Sun')
    // step: Reload the page with F5
    // expect: The homepage and article page load without any login, sign-up, or paywall prompt
    // expect: The header shows anonymous-user options (e.g. 'Create account' / 'Log in') and never blocks reading
    // expect: The 'Solar System' article content is fully readable
    // expect: The internal link navigates to the linked article successfully
    // expect: After reload the article is still displayed without requiring authentication
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-03 Submit an empty search query and verify a blank result page with no search results", async ({ page }) => {
    // step: Click into the search bar without typing any characters
    // step: Verify the search bar is empty
    // step: Press Enter (or click the search button) to submit the empty query
    // step: Observe the resulting page
    // expect: The search results page opens with an empty query
    // expect: No article is opened and no result entries are listed
    // expect: The results area is blank (no search results displayed) and no unhandled exception, stack trace, or blank white screen error is shown
    // expect: The search bar remains available for a new query
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-04 Search with an invalid / non-existent term and verify 'no results' message", async ({ page }) => {
    // step: Click into the search bar
    // step: Type the invalid string 'qwzxjklvbnmzzyxwq123'
    // step: Press Enter to submit the search
    // step: Observe the search results page and the displayed message
    // expect: The search results page loads successfully
    // expect: No article page is opened
    // expect: The message 'There were no results matching the query' is displayed
    // expect: The entered query is retained in the search bar so it can be corrected
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-05 Search with text longer than 500 characters and verify maximum-length error message", async ({ page }) => {
    // step: Click into the search bar
    // step: Paste the prepared string of more than 500 characters
    // step: Confirm the pasted text length exceeds 500 characters
    // step: Press Enter to submit the search
    // step: Observe the message shown on the results page
    // expect: The search is submitted and the results page loads without crashing
    // expect: No article results are returned
    // expect: The error message 'An error has occurred while searching: Search request is longer than the maximum allowed length' is displayed
    // expect: The page remains usable and a shorter query can be entered afterwards
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
  test("TC-06 Boundary check: search with exactly 500 characters and with exactly 501 characters", async ({ page }) => {
    // step: Click into the search bar and paste the string of exactly 500 characters
    // step: Verify the character count is exactly 500
    // step: Press Enter to submit the search and record the page output
    // step: Return to the homepage and clear the search bar
    // step: Paste the string of exactly 501 characters and verify the count is 501
    // step: Press Enter to submit the search and record the page output
    // expect: For the 500-character query the length error is NOT shown; the results page loads and displays either matching results or 'There were no results matching the query'
    // expect: For the 501-character query the error message 'An error has occurred while searching: Search request is longer than the maximum allowed length' is displayed
    // expect: No application crash, timeout, or truncated/garbled page layout occurs in either case
    await page.goto(BASE_URL);
    await expect(page).toHaveURL(/.*/);
    await expect(page.locator("body")).toBeVisible();
  });
});
