import { test, expect } from "@playwright/test";

// Generated by One Touch E2E for BOK-21.
const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

test.describe("ViewArticleOnWikipedia (api)", () => {
  test("TC-01 Anonymous user can search a topic and view the Wikipedia article (happy path)", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-02 Search with empty input returns a blank search result page", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-03 Search with invalid/nonsense text shows 'no results matching the query' message", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-04 Search with text longer than the maximum allowed length shows length error message", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-05 Boundary check: search query of exactly 500 characters vs 501 characters", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-06 Search with special characters and leading/trailing spaces only", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
});
