import { test, expect } from "@playwright/test";

// Generated by One Touch E2E for BOK-21.
const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

test.describe("ViewArticleOnWikipedia (api)", () => {
  test("TC-01 Anonymous user searches for a valid topic and views the article successfully (happy path)", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-02 Submitting an empty search bar returns a blank page with no search results", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-03 Searching an invalid/nonsense term shows 'There were no results matching the query'", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-04 Search string longer than 500 characters returns maximum length error message", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-05 Boundary: search string of exactly 500 characters is accepted and 501 characters is rejected", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-06 Search containing only whitespace and special characters does not return an article", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
});
