import { test, expect } from "@playwright/test";

// Generated by One Touch E2E for BOK-21.
const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

test.describe("ViewArticleOnWikipedia (api)", () => {
  test("TC-01 Anonymous user searches a valid topic and views the Wikipedia article successfully", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-02 Submitting an empty search bar returns a blank page with no search results", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-03 Searching an invalid/nonexistent topic shows 'There were no results matching the query'", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-04 Searching text longer than 500 characters shows maximum length error message", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-05 Boundary: search text of exactly 500 characters is accepted without length error", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
  test("TC-06 Special characters only in search bar are handled gracefully", async ({ request }) => {
    const response = await request.get(BASE_URL);
    expect(response.status()).toBeLessThan(500);
  });
});
